### ISSUE TITLE
V5 - bug(postgraphile watcher): Creating/deleting table nulls out schema

### ISSUE THREAD

**Issue by peteromano** [graphile/crystal#1761]
### Summary

When adding or deleting a table, postgraphile schema becomes "empty" (until reloading postgraphile.)

### Steps to reproduce

1) Run `docker compose up -d` (see compose file below)
2) Run `docker compose exec node sh`
3) Run command: `npx postgraphile -P postgraphile/presets/amber -e -c postgresql://postgres@postgres/postgres -S postgresql://postgres@postgres/postgres -p 9000 --host 0.0.0.0 -s public -w`
4) Visit pgAdmin at `http://localhost:7000` in browser
5) Login to pgAdmin (`postgres@example.com` / `1337`)
6) Register server (`postgres` server, `postgres` username, no password)
7) Add table "example", under public schema, with: "id" field, INTEGER, primary key, not null
8) Quit postgraphile
9) Restart postgraphile (step 3)
10) Visit ruru at `http://localhost:9000/graphql` in browser, check schema ("examples" graphql calls should be there)
11) Repeat step 7, with new table name "test"
12) Repeat step 10, notice schema is now empty

The same results occur when deleting tables as well.

However, if only changing columns, the watcher works as expected.

This is confirmed to be a postgraphile watcher issue (not specific to ruru.)

### Expected results

GraphQL generated calls for "examples" and "tests" should show in ruru

### Actual results
Schema becomes "empty" (see image)

![image](https://github.com/graphile/crystal/assets/392387/3e996e27-a7a6-4558-90b8-85c2a40b3b3e)

### Additional context

```
# docker-compose.yml

version: '3.7'


services:

  node:
    image: node:18-alpine
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgresql://postgres@postgres/postgres

  postgres:
    image: postgis/postgis:15-3.4
    command: ["postgres", "-c", "work_mem=64MB", "-c", "max_connections=15", "-c", "shared_buffers=500MB"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /var/lib/postgresql/data

  pgadmin:
    depends_on:
      - pg
    image: dpage/pgadmin4
    ports:
      - "7000:80"
    environment:
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: 0
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-1337}
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgadmin:
```

### Possible Solution

🤷‍♂️ 😢

**Comment by benjie** [comment]
I'm not going to attempt to reproduce this using Docker, that seems needlessly complicated. But just using PostGraphile and creating the tables you state in a new blank database works as expected, with Ruru automatically reflecting the changes.

You should have a look in the network tools and see if you can figure out what's going on that's making your Docker setup break. Perhaps you are running the server through `nodemon` or similar and the server is restarted after notifying the client of a change?

Please try and reproduce this in the simplest possible setup - just using Node and Postgres.

**Comment by peteromano** [comment]
Thanks for validating that the most base case works! Interesting that you're pointing towards a network/docker issue.. Funny that the column updating works though. 🤔 

Will think about this more.... Thanks, B!

**Comment by benjie** [comment]
I wasn't really suggesting it was a network issue, more that _something_ is going awry and watching what comes over the network might give a hint. For example, if the connection drops and reconnects then that suggests the server is restarting. If the connection remains but no events occur then that might be something else. It sounds like the event is received but then introspection fails... seeing _why_ it fails (what's the result of introspection?) might help shed some light on what's going on.

**Comment by peteromano** [comment]
@benjie Here's a screencast of the repro, using:

* Node v16.20.2
* WSL2 Ubuntu host
* postgres:15.4 container (Docker)

Nothing in the DB logs complains, will try with verbose debug logging and keep digging in more later, but for now, you can see the screencast below.

https://github.com/graphile/crystal/assets/392387/b263ef39-cc36-4b88-8acb-ebb4d8385d32

**Comment by benjie** [comment]
Super weird :man_shrugging: 

Maybe it's already fixed in the next version because I'm not seeing it :man_shrugging:

**Comment by peteromano** [comment]
Definitely super weird - that's exactly what I said lol

**Comment by peteromano** [comment]
@benjie Confirmed, it is indeed pgAdmin. Using the GUI or Query Tool causes the issue, but looking through SQL logs, I'm not sure why..

Queries look the same whether from pgAdmin or another tool or psql, so I can only guess maybe it's newline chars from the pgAdmin query text into pg or something..

**Comment by benjie** [comment]
@peteromano Please can you see if this is still an issue with the latest PostGraphile beta? I tweaked some things which might or might not be related.

**Comment by peteromano** [comment]
Hey @benjie !

Sorry I missed your comment. 

I'm on the latest beta (5.0.0-beta.15), and still have this issue, however i pinpointed the issue: Transaction blocks cause this.

Watching ruru, if I do this:

```
begin;
create table myschema.A (x integer);
commit;

begin;
alter table myschema.A add column y integer;
commit;
```

`allMySchemaAs` etc is generated and showing in real-time.

However, this:

```
begin;
create table myschema.A (x integer);

alter table myschema.A add column y integer;
commit;
```

Presents the issue mentioned above. The schema "nulls" out in ruru, showing just "id, node, query", and isn't just a ruru issue, the app itself can't find the schema unless i restart the server.

**Comment by benjie** [comment]
Should be fixed in `postgraphile@5.0.0-beta.16` (available now)

**Comment by peteromano** [comment]
Wow.  Confirmed to be fixed.

Why can't every project/team work as well as you guys? lol

Thanks so much @benjie! This is gonna be a great first impression for users when setting up their schema
